package jg.cryptodroid.enums;

public enum CoinList {
    LTC, ETH, XRP, BCH, EOS, XLM, ADA, XMR, TRX, DASH, GAME, BCC, BTG, KZC,
    XIN, ZEC, GNT, OMG, FTO, PAY, REP, ZRX, BAT, NEU, LSK, STORJ, LINK, DNT,
    POWR, WPR, BNB, ZEN, RVN, NULS, PAX, DATA, VET, NANO, QKC, GVT, ICX, PHX,
    ARN, KEY, NPXS, CDT, ZIL, WAN, VIB, AGI, RLC, NCASH, IOTA, SNGLS, POA,
    SNT, RCN, SNM, DOCK, IOTX, YOYO, IOST, NEO, NEBL, INS, WTC, CND, ONT, VIA,
    POLY, PPT, STORM, STEEM, APPC, ARDR, HOT, TNB, ETC, DENT, ENG, ELF, DLT,
    MFT, THETA
}
